### ISSUE TITLE
µTCA: no power to Sayma when RTM is plugged

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/sinara#571]
Blue and red LEDs on Sayma AMC blink rapidly, and all voltage LEDs on Sayma AMC are off.

**Comment by gkasprow** [comment]
Does it start with AMC only?

**Comment by sbourdeauducq** [comment]
Yes.

**Comment by gkasprow** [comment]
did you try with another RTM?

**Comment by gkasprow** [comment]
And is it the AMC I shipped you recently? Rapid blinking looks like overcurrent issue that was fixed by slow start circuits added to recent hardware.

**Comment by gkasprow** [comment]
And please test it in leftmost and rightmost slots.

**Comment by sbourdeauducq** [comment]
> And is it the AMC I shipped you recently?

Yes. It has the slow-start circuit rework. Previously, AMCs never started at all in the crate.
The RTM powers up when using the ATX supply.

**Comment by gkasprow** [comment]
@wizath do you remember if some particular MCH settings were necessary to make power working?

**Comment by gkasprow** [comment]
@sbourdeauducq I'm pretty sure you have to setup current limit on your MCH.

**Comment by jbqubit** [comment]
@gkasprow @wizath This is super annoying! @sbourdeauducq is now experiencing the same type of power-on problems that caused me to send boards back to WUT middle of June. If there are configuration steps needed for MCH please document on [sinara-hw/sayma](https://github.com/sinara-hw/sinara/wiki/Sayma).

**Comment by wizath** [comment]
I don't think there is any configuration to do - since we used @jbqubit's MCH and I didn't change anything.

**Comment by jbqubit** [comment]
I've made modifications to the default behavior of MCH. I know I've discussed this with @gkasprow. The power-on behavior is set in a configuration file uploaded to the MCH. Here's the [default](https://github.com/jbqubit/sinara-testing/blob/master/sayma/tools/nat_mch_running_cfg_factory.txt) that ships with NAT Native-R6. [Here's](https://github.com/jbqubit/sinara-testing/blob/master/sayma/tools/nat_mch_startup_cfg_sinara.txt) a version that I've used in the past but not validated on functioning boards. Given what we know now about inrush current, using a one second delay between power-on of each AMC slot seems wise.

**Comment by gkasprow** [comment]
@sbourdeauducq could you post logs from MMC?

**Comment by marmeladapk** [comment]
It's likely that we fixed this issue, at least on one Sayma, the one marked with "F" on an orange sticker.

**Comment by marmeladapk** [comment]
Sometimes only AMC gets power, RTM doesn't start.

**Comment by sbourdeauducq** [comment]
@gkasprow / @marmeladapk Did you find a solution?

**Comment by gkasprow** [comment]
Jakub will send you update with disabled RTM power negotiation. In a few days we will get brand new MCH so will be able to recreate the issue.

**Comment by sbourdeauducq** [comment]
Any progress on this?

**Comment by wizath** [comment]
[fw_forced_rtm.tar.gz](https://github.com/sinara-hw/sinara/files/2344672/fw_forced_rtm.tar.gz)

Power level switch is set to 0x01 after enabling power for AMC, so RTM boots straight after.

**Comment by sbourdeauducq** [comment]
Nope, that doesn't work. Same situation as before: There is power when the AMC alone is plugged in, but everything shuts down then the RTM is also plugged. Have you tested it?

**Comment by wizath** [comment]
Tested on NAT PSU+MCH, RTM gets power just after AMC. But this is Vadatech crate and fixed boards with current limiters.

**Comment by sbourdeauducq** [comment]
Does the RTM need a current limiter too?
It doesn't work either with the RTM I received from Technosystem today, on which all known reworks are supposed to be applied.

**Comment by gkasprow** [comment]
Bran new PSU is on the way. We will recreate the problem with it.

**Comment by gkasprow** [comment]
We've just received brand new NAT crate, 2 MCHs, 4 PSUs so have all we need to recreate the problem.

**Comment by gkasprow** [comment]
The boards you received work perfectly with NAT PSU and MCH.
Please post here what MCH and PSU say in logs. It looks like you have to adjust current limit in MCH.

**Comment by sbourdeauducq** [comment]
I don't know how you can expect anything other than IPMI snafu...
```
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ScanPM: ...
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
no PM for fru_id=51
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
no PM for fru_id=52
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
no PM for fru_id=53
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ScanPM: ...
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
no PM for fru_id=51
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
no PM for fru_id=52
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
no PM for fru_id=53
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
AMC1(5): Communication regained !
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): REQ(I2C=0x72) failed on bus 1 - no ACK
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
```

**Comment by sbourdeauducq** [comment]
Sometimes there is this too:
```
ipmi_SendFru(5): timeout - no response for REQ: 0x20->0x72, Seq=3 GET_DEVICE_ID_REQ
PM(50,5): FRU 5 - de-assert #ENABLE
PM(50,5): Deassert #ENABLE
PM(50,5): FRU 5 - assert #ENABLE
PM(50,5): Assert #ENABLE
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
```

**Comment by sbourdeauducq** [comment]
If I unplug the RTM then the mess stops:
```
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ScanPM: ...
no PM for fru_id=51
no PM for fru_id=52
no PM for fru_id=53
AMC1(5): Communication regained !
AMC1(5): AMC needs 8.0 Amps power
....
AMC1(5): Handle=0x01 - closed
bp_fru: power chan=5, current limit=8.0 A
PwrAllocate(fru 5 chan 5): allocating 8.0 A granted (available 44.5 A)
pm_EnablePayloadPwr(50,5):
LSHM(0): CM sensor 68 LUN 0 <unknown> hotswap M0->M1
LSHM(0): CM sensor 68 LUN 0 <unknown> hotswap M1->M2
LSHM(0): FRU 5 sensor 67 LUN 0 'HS 005 AMC1' hotswap M2->M3
LSHM(0): FRU 5 sensor 67 LUN 0 'HS 005 AMC1' hotswap M1->M2
LSHM(0): FRU 5 sensor 67 LUN 0 'HS 005 AMC1' hotswap M2->M3
PM(50,5):Enable PP (primSite:1 secSite:0)
pm_PP_good(5): Failure: power channel state=0x0b
pm_PP_good(5): Failure: power channel state=0x0b
PM(50,5): new state=0x1b
pm_processEvent PM(50): channel(5) new state=0x1b
LSHM(0): FRU 5 sensor 67 LUN 0 'HS 005 AMC1' hotswap M3->M4
LSHM(0): FRU 5 sensor 67 LUN 0 'HS 005 AMC1' hotswap M3->M4
ScanPM: ...
no PM for fru_id=51
no PM for fru_id=52
no PM for fru_id=53
ScanPM: ...
no PM for fru_id=51
no PM for fru_id=52
no PM for fru_id=53
```

and restarts as soon as I hotplug it:
```
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
ipmiMsgSender(5): RSP(I2C=0x72) failed on bus 1 result -8
```

**Comment by sbourdeauducq** [comment]
The behavior is the same with the boards you sent, and those I had (after reflashing).

**Comment by gkasprow** [comment]
I'm back from holidays.
I plugged the AMC board to bran new uTCA crate and AMC works, but when I plug the RTM, all AMC LEDs blink quickly. So it looks like we have similar issue here.

**Comment by sbourdeauducq** [comment]
There is only one power supply slot in the chassis I have.

**Comment by gkasprow** [comment]
Funny thing, I got same symptoms when plug the RTM loopback...There is almost nothing on it

**Comment by gkasprow** [comment]
OK, known issue - MCH sometimes does not wakeup when USB plug is inserted

**Comment by gkasprow** [comment]
And PM needs to be inserted to right slot. PM slot assignment can be programmed by NATView application.

**Comment by gkasprow** [comment]
strange, I cannot recreate the problem any more. The only conclusion I came about is that the mTCA crate disconnects the management power for a moment which resets the MMC CPU. It is repeated a few times per second. It looks like the power consumption from 3.3V was too high.

**Comment by hartytp** [comment]
> OK, known issue - MCH sometimes does not wakeup when USB plug is inserted

What's the deal here? Those NAT MCHs were expensive, so why are they shipping with known bugs like this? Are they actually a high-quality component we can rely on, or just another shoddy over-priced piece of kit targeting physicists?

More generally, it strikes me as crazy that getting Sayma to power up in a rack is proving to be this much work. AFAICT, at least some of the blame lies with the NAT components we're using.

Since we've agreed to drop support for the LLRFBP in the next design revision, we can use a wide variety of uTCA AMC+RTM chassis from other vendors. Would it be quicker to find a higher-quality chassis + MCH from another vendor?

**Comment by gkasprow** [comment]
We also use MTCA stuff from Vadatech. They do not conform with MTCA specification and probably that's why some of the issues appeared with NAT.
But now I have 2 NAT sets in the lab and can finally debug and solve the issues.

**Comment by hartytp** [comment]
@gkasprow okay, well that's good. It will make testing much easier if we all have a consistent setup, so we don't have to ask questions like "which PSU are you using" when we discover issues.

I would still like to know why NAT are shipping MCHs with known issues like "it doesn't work when you power it up with the USB plugged in". That doesn't give me much confidence in the quality of their hardware or testing.

**Comment by gkasprow** [comment]
You can always enable power to all modules, ignoring all the MMC issues, but I want to do it properly.

**Comment by gkasprow** [comment]
Yesterday I had visit of my colleague from CERN in my lab and he gave me some advices how to handle the NAT stuff. The equipment is good quality but can be configured in so many ways that cause confusion.
The USB plug is probably foreseen for bootloader only afor advanced users and the main diagnostic and configuration tool is NatView software written in Java to runs on all platforms. I had no issues running it on WIndows.  Diagnostics over usb is very limited.
The same with PSU - their configuration in slots (main/redundant) is configurable. So that;s why not all combinations work. And that's why I was surprised by that fact.
I have experience with Vadatech equipment which is much simpler and you can configure almost nothing. And the documentation is poor. And its quality is questionable. The fan trays broke several times, the same with MCH. I had to do reverse engineering of MCH to disable spread spectrum in PCIe hub :)
NAT is very flexible and needs good understanding to use it properly. 
Once I manage to setup it and prove it works in my lab, will create a guide how to build and configure working setup.

**Comment by sbourdeauducq** [comment]
> And PM needs to be inserted to right slot.

Again, the crate I'm using has only one slot, in the left.

> written in Java
> NAT is very flexible and needs good understanding to use it properly.

Let's call it poor design. We just want to power up a few boards and spin up a couple fans, for God's sake.

> You can always enable power to all modules, ignoring all the MMC issues,

You keep saying this, but I have not seen it demonstrated. When I attempted it, the whole crate shut down, but that was before adding the current limit to Sayma. Is it working now?

> More generally, it strikes me as crazy that getting Sayma to power up in a rack is proving to be this much work

This seems to be standard fare with uTCA according to a few engineers I've talked to, and one main reason why I was opposed to using it.

**Comment by gkasprow** [comment]
@sbourdeauducq It worked for me with permanently enabled power supplies. Current limit that I added helped - before the inrush current was too high.  So it should work in your crate too. Remember that you cannot make hotplug.
Now I want to fully conform with NAT requirements because they follow MTCA specification strictly.
We have MTCA systems installed in numerous places, but so far almost all of them use Vadatech crates. That's why there were no issues with supply. We switched to NAT due to several reasons and now it's my responsibility to make it working.

**Comment by gkasprow** [comment]
With 2 power modules, the AMC+RTM works properly. It looks like AMC is drawing too much current from 3.3V MP

**Comment by gkasprow** [comment]
The MTCA spec says that it should not exceed 150mA. Sayma is consuming far less. So maybe inrush current is an issue here. I observe on the scope that management power arrives, but after a few ms later starts falling down which causes MMC reset and the process repeats. Maybe 3.3VMP rail switch consumes too much during power on...

**Comment by gkasprow** [comment]
The spec says: The Power Modules shall support MP inrush current up to 270 mA
for 200 ms to each AMC slot

**Comment by hartytp** [comment]
Good catch!

**Comment by gkasprow** [comment]
The RTM consumes some current because I2C switch outputs have 2k2 pullups to 3V3MP which adds a few mA to the bill. And these a few mA are too much for 3.3V management rail.

**Comment by jbqubit** [comment]
> The fix is easy - change initialisation sequence in MMC so it initialises GPIOs after MMC negotiates power.

Please link to updated MMC firmware.

**Comment by gkasprow** [comment]
@wizath please publish update once you implement the fix.

**Comment by sbourdeauducq** [comment]
Nope.

```
ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
ipmiMsgSender(91): REQ(I2C=0x74) failed on bus 2 - no ACK
R(91,2,2)ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
```

```
ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
ipmi_SendFru(91): timeout - no response for REQ: 0x20->0x74, Seq=61 GET_DEVICE_ID_REQ
ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
```

```
ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
RTM2(91): Communication regained !
ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
ipmiMsgSender(6): REQ(I2C=0x74) failed on bus 2 - no ACK
ipmiMsgSender(6): RSP(I2C=0x74) failed on bus 2 result -8
```

etc. etc.

As before, errors disappear and AMC gets powered when RTM is removed.

**Comment by sbourdeauducq** [comment]
@wizath Where are your RTMs? Should I send you one immediately?

**Comment by gkasprow** [comment]
@sbourdeauducq do all the LEDs on the AMC panel blink quickly?

**Comment by sbourdeauducq** [comment]
No, only the green one at the bottom is blinking.

**Comment by gkasprow** [comment]
so it is not related with the issue that we solved recently.

**Comment by gkasprow** [comment]
@marmeladapk can you please try the recent firmware on the 6-slot chassis you have in Maryland?

**Comment by sbourdeauducq** [comment]
I tried adding the following to the MCH settings file:
```
amc_pwr_on = 5, 100, 0
amc_pwr_on = 6, 100, 0
amc_pwr_on = 7, 100, 0
amc_pwr_on = 8, 100, 0
```

This has stopped the stream of error messages on the telnet interface (what a horrible user interface - you cannot type any command while the errors are scrolling, and a constant stream of errors seems to be a common occurrence with this IPMI trash). But, of course, the Sayma is still not powered - no matter if the RTM is plugged in or not.

**Comment by gkasprow** [comment]
are you sure that slot numbering in your chassis is as above?

**Comment by sbourdeauducq** [comment]
It's a NATIVE-R5 and I put the Sayma cards close to the MCH. From what I understand from the documentation, this is correct?
The disappearance of the errors also suggests that I am targeting the correct slot numbers.

**Comment by marmeladapk** [comment]
@jbqubit has the same crate in his lab (and we encountered same problems as @sbourdeauducq).

**Comment by gkasprow** [comment]
@marmeladapk did you update firmware? Known overcurrent issue was fixed.

**Comment by marmeladapk** [comment]
Yes, an update that @wizath sent me didn't help.

**Comment by wizath** [comment]
You tried latest firmware? From https://github.com/sinara-hw/sinara/issues/571#issuecomment-426252827

**Comment by marmeladapk** [comment]
@wizath No, I tried the one you sent me on 26th Sept.

**Comment by sbourdeauducq** [comment]
@gkasprow Can you prioritize fixing this? When you advocated for µTCA you said it would be trouble-free, but the reality is very different; 2 years later the board still doesn't get power.

**Comment by gkasprow** [comment]
@jbqubit can you upgrade the MMC firmware and see if the problem persists?  I cannot recreate this issue with my setup.

**Comment by jbqubit** [comment]
I updated MMC firmware to [version](https://github.com/sinara-hw/sinara/issues/571#issuecomment-426252827) recommended by @wizath. Now I see the following.
- can boot AMC+RTM in NATIVE-R9 with two PSU in crate  
- can /not/ boot AMC+RTM in NATIVE-R9 with only one PSU in crate  
- Ethernet over uTCA backplane: can pin AMC using NAT MCH as Ethernet switch
- can generate sinusoidal output from RTM 


```
$ artiq_flash -t sayma start
Open On-Chip Debugger 0.10.0-00013-gbb7beda (2018-02-13-15:56)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
none separate
adapter speed: 5000 kHz
Info : clock speed 5000 kHz
Error: JTAG scan chain interrogation failed: all ones
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: xc7.tap: IR capture error; saw 0x3f not 0x01
Warn : Bypassing JTAG setup events due to errors
Info : gdb server disabled
RTM FPGA XADC:
TEMP 33028232.44 C
VCCINT 196608.000 V
VCCAUX 196608.000 V
VCCBRAM 196608.000 V
VPVN 196608.000 V
VREFP 196608.000 V
VREFN 196608.000 V
VCCPINT 196608.000 V
VCCPAUX 196608.000 V
VCCODDR 196608.000 V
AMC FPGA XADC:
TEMP 33028232.44 C
VCCINT 196608.000 V
VCCAUX 196608.000 V
VCCBRAM 196608.000 V
VPVN 196608.000 V
VREFP 196608.000 V
VREFN 196608.000 V
VCCPINT 196608.000 V
VCCPAUX 196608.000 V
VCCODDR 196608.000 V
```

```
|  \/  (_) ___|  ___  / ___|
| |\/| | \___ \ / _ \| |    
| |  | | |___) | (_) | |___ 
|_|  |_|_|____/ \___/ \____|

MiSoC Bootloader
Copyright (c) 2017-2018 M-Labs Limited

Bootloader CRC passed
Gateware ident 4.0.dev+1401.g20cddb6a.dirty;masterdac
Initializing SDRAM...
DQS initial delay: 111 taps
Write leveling scan:
Module 3:
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000101111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110100000000000000000000000000000000000000000000
Module 2:
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111010000000000000000000000000000000000
Module 1:
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111101111101000000000000000000000000000000000000000000000000000000000000000000
Module 0:
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111101101101000000000000000000000000000000000000000000000000000000000000000000000
DQS initial delay: 111 taps
Write leveling: 94 99 120 116 done
Read leveling scan:
Module 3:
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111011100010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Module 2:
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111001100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Module 1:
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Module 0:
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Read leveling: 246+-89 237+-96 213+-86 195+-93 done
SDRAM initialized
Memory test passed

Booting from flash...
Starting firmware.
[     0.000005s]  INFO(runtime): ARTIQ runtime starting...
[     0.003869s]  INFO(runtime): software ident 4.0.dev+1401.g20cddb6a.dirty;masterdac
[     0.011436s]  INFO(runtime): gateware ident 4.0.dev+1401.g20cddb6a.dirty;masterdac
[     0.019034s]  INFO(runtime): log level set to INFO by default
[     0.024732s]  INFO(runtime): UART log level set to INFO by default
[     0.030873s]  INFO(board_artiq::slave_fpga): Loading slave FPGA gateware...
[     0.037823s]  INFO(board_artiq::slave_fpga):   magic: 0x5352544d, length: 0x000bd5d0
[     0.045549s]  INFO(board_artiq::slave_fpga):   DONE before loading
[     1.036920s]  INFO(board_artiq::slave_fpga):   ...done
[     1.040731s]  INFO(board_artiq::serwb): waiting for AMC/RTM serwb bridge to be ready...
[     1.075461s]  INFO(board_artiq::serwb):  ...done.
[     1.078830s]  INFO(board_artiq::serwb): RTM to AMC link test...
[     2.561133s]  INFO(board_artiq::serwb):   ...passed
[     2.564678s]  INFO(board_artiq::serwb): AMC to RTM link test...
[     4.046986s]  INFO(board_artiq::serwb):   ...passed
[     4.050539s]  INFO(board_artiq::serwb): Wishbone test...
[     5.982573s]  INFO(board_artiq::serwb):   ...passed
[     5.986428s]  INFO(board_artiq::serwb): RTM gateware version 4.0.dev+1401.g20cddb6a.dirty
[     5.994281s]  INFO(runtime): press 'e' to erase startup and idle kernels...
[     6.994006s]  INFO(runtime): continuing boot
[     7.256352s]  INFO(board_artiq::si5324): waiting for Si5324 lock...
[    10.997300s]  INFO(board_artiq::si5324):   ...locked
[    11.001064s]  INFO(board_artiq::hmc830_7043::hmc830): loading HMC830 configuration...
[    11.008998s]  INFO(board_artiq::hmc830_7043::hmc830):   ...done
[    11.014651s]  INFO(board_artiq::hmc830_7043::hmc830): setting HMC830 dividers...
[    11.022115s]  INFO(board_artiq::hmc830_7043::hmc830):   ...done
[    11.027937s]  INFO(board_artiq::hmc830_7043::hmc830): waiting for HMC830 lock...
[    11.035356s]  INFO(board_artiq::hmc830_7043::hmc830):   ...locked
[    11.041586s]  INFO(board_artiq::hmc830_7043::hmc7043): enabling HMC7043
[    11.058288s]  INFO(board_artiq::hmc830_7043::hmc7043): loading configuration...
[    11.075772s]  INFO(board_artiq::hmc830_7043::hmc7043):   ...done
[    11.080454s]  INFO(board_artiq::hmc830_7043::hmc7043): testing GPO...
[    11.087567s]  INFO(board_artiq::hmc830_7043::hmc7043):   ...passed
[    11.103781s]  INFO(board_artiq::ad9154): AD9154-0 initializing...
[    11.115584s]  INFO(board_artiq::ad9154):   ...done
[    11.189460s]  INFO(board_artiq::ad9154): AD9154-0 running PRBS test...
[    12.195823s]  INFO(board_artiq::ad9154):   ...passed
[    12.199471s]  INFO(board_artiq::ad9154): AD9154-0 running STPL test...
[    12.206259s]  INFO(board_artiq::ad9154):   c0 errors: 0
[    12.211463s]  INFO(board_artiq::ad9154):   c1 errors: 0
[    12.216673s]  INFO(board_artiq::ad9154):   c2 errors: 0
[    12.221882s]  INFO(board_artiq::ad9154):   c3 errors: 0
[    12.226807s]  INFO(board_artiq::ad9154):   ...passed
[    12.241790s]  INFO(board_artiq::ad9154): AD9154-0 initializing...
[    12.249204s]  INFO(board_artiq::ad9154):   ...done
[    12.333687s]  INFO(board_artiq::ad9154): AD9154-1 initializing...
[    12.345446s]  INFO(board_artiq::ad9154):   ...done
[    12.419310s]  INFO(board_artiq::ad9154): AD9154-1 running PRBS test...
[    13.425663s]  INFO(board_artiq::ad9154):   ...passed
[    13.429309s]  INFO(board_artiq::ad9154): AD9154-1 running STPL test...
[    13.436094s]  INFO(board_artiq::ad9154):   c0 errors: 0
[    13.441304s]  INFO(board_artiq::ad9154):   c1 errors: 0
[    13.446513s]  INFO(board_artiq::ad9154):   c2 errors: 0
[    13.451723s]  INFO(board_artiq::ad9154):   c3 errors: 0
[    13.456645s]  INFO(board_artiq::ad9154):   ...passed
[    13.471631s]  INFO(board_artiq::ad9154): AD9154-1 initializing...
[    13.479046s]  INFO(board_artiq::ad9154):   ...done
[    13.552951s]  INFO(board_artiq::jesd204sync): verifying SYSREF margins at DAC-0...
[    13.649231s]  INFO(board_artiq::jesd204sync):   margins: -36 +33
[    13.655153s]  INFO(board_artiq::jesd204sync): verifying SYSREF margins at DAC-1...
[    13.750257s]  INFO(board_artiq::jesd204sync):   margins: -2 +66
[    13.754856s] ERROR(runtime): failed to align SYSREF at DAC: SYSREF margins at DAC are too small, board needs recalibration
[    13.765888s]  INFO(board_artiq::hmc542): card 0 channel 0 set to 4 dB
[    13.774395s]  INFO(board_artiq::hmc542): card 0 channel 1 set to 4 dB
[    13.781611s]  INFO(board_artiq::hmc542): card 1 channel 0 set to 4 dB
[    13.788827s]  INFO(board_artiq::hmc542): card 1 channel 1 set to 4 dB
[    13.796044s]  INFO(board_artiq::hmc542): card 2 channel 0 set to 4 dB
[    13.803260s]  INFO(board_artiq::hmc542): card 2 channel 1 set to 4 dB
[    13.810477s]  INFO(board_artiq::hmc542): card 3 channel 0 set to 4 dB
[    13.817693s]  INFO(board_artiq::hmc542): card 3 channel 1 set to 4 dB
[    13.824957s]  INFO(runtime): using MAC address 34-45-32-12-ff-20
[    13.829723s]  INFO(runtime): using IP address 192.168.1.129
[    13.837058s]  INFO(runtime::mgmt): management interface active
[    13.850193s]  INFO(runtime::session): accepting network sessions
[    13.855698s]  INFO(runtime::session): running startup kernel
[    13.860645s]  INFO(runtime::session): no startup kernel found
[    13.866348s]  INFO(runtime::session): no connection, starting idle kernel
[    13.873219s]  INFO(runtime::session): no idle kernel found
[   262.074998s]  INFO(runtime::session): new connection from 192.168.1.145:41988
[   262.108619s]  INFO(runtime::kern_hwreq): resetting RTIO
[   349.543381s]  INFO(runtime::session): no connection, starting idle kernel
[   349.549240s]  INFO(runtime::session): no idle kernel found
[   356.142295s]  INFO(runtime::session): new connection from 192.168.1.145:41990
[   356.177971s]  INFO(runtime::kern_hwreq): resetting RTIO
[   356.182161s] ERROR(runtime::rtio_mgt): RTIO sequence error involving channel 46
[   356.189405s] ERROR(runtime::rtio_mgt): RTIO collision involving channel 6
```

**Comment by hartytp** [comment]
Okay, good, we're getting there...

> can /not/ boot AMC+RTM in NATIVE-R9 with only one PSU in crate

@gkasprow any ideas what the cause of this should be?

Am I right in thinning that @sbourdeauducq only has one PSU in his crate, so this is consistent with the issues he was having?

**Comment by sbourdeauducq** [comment]
> @sbourdeauducq only has one PSU in his crate

That is correct.

**Comment by gkasprow** [comment]
@jbqubit can you connect terminal to the MMC and see what it says?
Did you try to run Natview software and connect with MCH via Ethernet? We have identical configuration and it works, so it looks like some PSU or backplane settings

**Comment by gkasprow** [comment]
@jbqubit can you make a video showing behaviour of Sayma front panel LEDs while booting? Do they blink in any way?

**Comment by gkasprow** [comment]
@sbourdeauducq I have some idea what could go wrong in your crate. Please do one thing  - short pin 1 and pin 8 of T3 and short pin 1 and pin 8 of T14. I marked it with blue line on PCB drawing. The transistors reside close to the RTM connector.
![obraz](https://user-images.githubusercontent.com/4325054/48962352-1bbc2400-ef7f-11e8-8fb3-68836709094f.png)


And check if AMC and RTM gets power. Do not insert RTM board into powered crate because both AMC or RTM can be damaged.
If only AMC gets power, please also short pin 1 and pin 2 of T5.
![obraz](https://user-images.githubusercontent.com/4325054/48962208-22e23280-ef7d-11e8-831d-869152a34e01.png)

If RTM gets power, please remove short on T3 - the one closer to the board edge and check if it still gets power.

**Comment by sbourdeauducq** [comment]
OK, will do when I come back from travels (in 3/4 weeks)

**Comment by gkasprow** [comment]
@jbqubit could you do such test as well? Just short transistors and let me know if it boots from single supply.

**Comment by marmeladapk** [comment]
@bradbqc shorted those transistors earlier and now his Sayma is restarting every ~60 seconds as he wrote in https://github.com/m-labs/artiq/issues/1064#issuecomment-442926743 . This doesn't depend on those shorts as they're removed right now. He's using latest mmc firmware.

**Comment by gkasprow** [comment]
did he measure current consumed by RTM from 3V3MP?
Is the same problem with RTM plugged?

**Comment by marmeladapk** [comment]
Without RTM connected Sayma doesn't reboot. @bradbqc, could you post your measurements?

**Comment by sbourdeauducq** [comment]
@gkasprow AFAICT this is still not resolved and will continue to be a problem with Sayma v2. Do you have a crate to reproduce it?

**Comment by gkasprow** [comment]
Did you try to short these transistors?

**Comment by sbourdeauducq** [comment]
No. Should I expect a different result than https://github.com/sinara-hw/sinara/issues/571#issuecomment-442969236 ?

**Comment by gkasprow** [comment]
It's quite possible that the board is damaged in some way. THe boards suffered a lot during transport.

**Comment by gkasprow** [comment]
It's quite possible that the board is damaged in some way. THe boards suffered a lot during transport.

**Comment by gkasprow** [comment]
The same board was working correctly before and got power from uTCA.

**Comment by sbourdeauducq** [comment]
> Please do one thing - short pin 1 and pin 8 of T3 and short pin 1 and pin 8 of T14.

RTM now gets power, AMC front panel LEDs are on but not power LEDs.

**Comment by sbourdeauducq** [comment]
> If RTM gets power, please remove short on T3 - the one closer to the board edge and check if it still gets power.

No effect.

**Comment by sbourdeauducq** [comment]
Well, those results probably don't mean much, because I can't get any AMC to power up anymore, even without the shorts and without the RTM, and on two different AMCs. This µTCA stuff is really obnoxious.

**Comment by sbourdeauducq** [comment]
Okay, it turns out that I had ``amc_pwr_on`` lines forgotten in the MCH configuration, and those interfere with Sayma power (It's another prime example of µTCA design that a feature supposed to force board power on actually turns them off...)

With T14 shorted both AMC and RTM now turn on! Now trying to short both T14 and T3...

**Comment by sbourdeauducq** [comment]
Also works (AMC+RTM) with both T14 and T3 transistors shorted.

**Comment by sbourdeauducq** [comment]
Tried another AMC. Also working with both transistors shorted.

**Comment by sbourdeauducq** [comment]
@gkasprow Are there further tests that you want me to do, or is this sufficient for you to determine what the problem is and ensure that Sayma v2 power will work properly without any reworks?

**Comment by gkasprow** [comment]
That's all. Thanks

**Comment by hartytp** [comment]
Nice! Great work all.

Will someone take care of documenting this all so that it's easy for people to set the racks up in future?

**Comment by sbourdeauducq** [comment]
@gkasprow Also, I suppose hotplug should be carefully tested if we claim it is supported.

**Comment by jbqubit** [comment]
HT3 calls for extensive power system testing related to uTCA, MCH, AMC and RTM cards. I added a new item to call explicitly for publishing the MCH configuration file. 

https://github.com/sinara-hw/sinara/issues/601#issuecomment-449977797

**Comment by jbqubit** [comment]
For comparison this is the configuration file I'm using.

https://github.com/jbqubit/sinara-testing/blob/master/sayma/tools/nat_mch_startup_cfg_sinara.txt

@sbourdeauducq If your boards are now working in the crate please close.

**Comment by sbourdeauducq** [comment]
> I added a new item to call explicitly for publishing the MCH configuration file.

With those lines removed, it's just the default MCH configuration file. This is good, since we don't want to have a different configuration file for every MCH model - hopefully we can work with the default settings for most MCHs.

@jbqubit What is more relevant is asking for the hotplugging to be tested.
